# Generated by Django 4.2.2 on 2023-06-18 11:07

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sname', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(10), app.models.not_s_A])),
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
            ],
        ),
    ]
